#ifndef CPP3_SMARTCALC_V2_0_1_VIEW_TRIGONOMETRYCALCULATIONTYPE_H_
#define CPP3_SMARTCALC_V2_0_1_VIEW_TRIGONOMETRYCALCULATIONTYPE_H_

namespace s21 {
enum class TrigonometryCalculationType { kRadians, kDegrees };
}

#endif  // CPP3_SMARTCALC_V2_0_1_VIEW_TRIGONOMETRYCALCULATIONTYPE_H_
