#ifndef CPP3_SMARTCALC_V2_0_1_COMMON_EXPRESSIONERRORCODE_H_
#define CPP3_SMARTCALC_V2_0_1_COMMON_EXPRESSIONERRORCODE_H_

namespace s21 {
enum class ExpressionErrorCode {
  kOk,
  kInvalidExpression,
};
}

#endif  // CPP3_SMARTCALC_V2_0_1_COMMON_EXPRESSIONERRORCODE_H_
